6 create timeline flow
noroff-alumni-assignment-group/alumni-network pull request #51
Opened 2023-03-22 14:46 UTC by marcusbugge

2023-03-22 14:49 UTC, ARodder commented on NoroffAlumni/src/main/java/no/experisAcadmey/trondheim/NoroffAlumni/mappers/UserMapper.java
find by name :)

2023-03-22 14:51 UTC, ARodder commented on NoroffAlumni/src/main/java/no/experisAcadmey/trondheim/NoroffAlumni/models/DTOs/postDTOs/PostDto.java
fjern target_topic og target_group som kun er string

2023-03-22 15:00 UTC, ARodder requested changes
forandre til findByName når den mapper usertopics og fjerne target_topic og target_group strings i PostDTO-en.

2023-03-23 10:38 UTC, Vegard46 approved these changes

2023-03-23 10:39 UTC, merged